mybatis:
  typeAliasesPackage: com.se.entity
  mapperLocations: classpath:/mapping/*.xml
spring:
  servlet:
    multipart:
      max-file-size: 100Mb
      maxRequestSize: 1000Mb
  datasource:
    url: jdbc:mysql://localhost:3306/code_dep?characterEncoding=utf-8&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:
    type: com.zaxxer.hikari.HikariDataSource
  data:
    neo4j:
      uri: bolt://localhost:11107
      username: neo4j
      password: 123
  output:
    ansi:
      enabled: always